name: Fantasy-Chess Pipeline

on:
  pull_request:
    branches: "*"

jobs:
  build-common:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
        with:
          gradle-version: 8.9

      - name: Grant execute permission for gradle
        working-directory: common
        run: chmod +x ./gradlew

      - name: Build with Gradle 8.9
        working-directory: common
        run: gradle build

      - name: Run Tests
        working-directory: common
        run: gradle test

  build-client:

    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs:
      - build-common

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
        with:
          gradle-version: 8.9

      - name: Grant execute permission for gradle
        working-directory: fantasychess-server
        run: chmod +x ./gradlew

      - name: Gradle Build
        working-directory: fantasychess-server
        run: gradle build

      - name: Run Tests
        working-directory: fantasychess-server
        run: gradle test

      - name: DistZip
        working-directory: fantasychess-client
        run: gradle distZip


  build-server:

    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs:
      - build-common

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
        with:
          gradle-version: 8.9

      - name: Grant execute permission for gradle
        working-directory: fantasychess-server
        run: chmod +x ./gradlew

      - name: Build with Gradle 8.9
        working-directory: fantasychess-server
        run: gradle build

      - name: Run Tests
        working-directory: fantasychess-server
        run: gradle test

      - name: Build Jar
        working-directory: fantasychess-server
        run: gradle bootJar

  documentation:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs:
      - build-server
      - build-client
      - build-common

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
        with:
          gradle-version: 8.9

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: client-build
          path: fantasychess-client/html/build/fantasychess-client-dist-1.0.0.zip
          retention-days: 5

      - name: Build Common Documentation
        working-directory: common
        run: |
          gradle javadoc
          zip -r build/docs/common-javadocs.zip build/docs/* 

      - name: Upload Common Documentation
        uses: actions/upload-artifact@v4
        with:
          name: common-javadocs
          path: common/build/docs/common-javadocs.zip
          retention-days: 5

      - name: Build Client Documentation
        working-directory: fantasychess-client
        run: |
          gradle javadoc
          zip -r html/build/docs/client-html-javadocs.zip html/build/docs/* 
          zip -r core/build/docs/client-core-javadocs.zip core/build/docs/* 

      - name: Upload Client HTML Documentation
        uses: actions/upload-artifact@v4
        with:
          name: client-html-javadocs
          path: fantasychess-client/html/build/docs/client-html-javadocs.zip
          retention-days: 5

      - name: Upload Client Core Documentation
        uses: actions/upload-artifact@v4
        with:
          name: client-html-javadocs
          path: fantasychess-client/core/build/docs/client-core-javadocs.zip
          retention-days: 5

      - name: Build Server Documentation
        working-directory: fantasychess-server
        run: |
          gradle javadoc
          zip -r build/docs/server-javadocs.zip build/docs/* 

      - name: Upload Server Documentation
        uses: actions/upload-artifact@v4
        with:
          name: common-javadocs
          path: fantasychess-server/build/docs/common-javadocs.zip
          retention-days: 5